# Generated by Django 4.0.3 on 2022-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0002_notes_tbl_works_tbl_appre_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('stdname', models.CharField(max_length=25)),
                ('details', models.TextField()),
            ],
        ),
    ]
