# Generated by Django 4.0.3 on 2022-04-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0004_meetcab_live_class_bthname_live_class_btime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
            ],
        ),
    ]
