# Generated by Django 4.0.3 on 2022-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0007_sendlink_btime_sendlink_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='class_video')),
                ('course', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
            ],
        ),
    ]
