# Generated by Django 4.0.3 on 2022-04-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Minor_Programmer', '0002_user_mp_mcs_user_mp_sname_user_mp_vrf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cfee', models.IntegerField()),
                ('cdetails', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Minor_Programmer.user_mp')),
            ],
        ),
    ]
