# Generated by Django 3.2 on 2021-05-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notification_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notititle', models.CharField(max_length=100)),
                ('notidate', models.DateField()),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
