# Generated by Django 4.0.3 on 2022-04-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_alter_admin_tbl_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='crs_img',
            field=models.FileField(default=1, upload_to='course'),
            preserve_default=False,
        ),
    ]
