# Generated by Django 3.2 on 2021-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_Tutor_Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=100)),
                ('url', models.FileField(upload_to='notes')),
                ('crs', models.CharField(max_length=100)),
                ('std', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
