# Generated by Django 4.0.5 on 2022-10-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_Tutor_Registration', '0005_works_tbl_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes_tbl',
            name='batch',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
